version: '3.3'

services:
  A:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/topologies/linear/nodeA-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a ws -hl -n nodeA
    networks:
      private-ndn-overlay:
        aliases:
          - nodea.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
  B:
    image: stefanolupo/ndn:ndn-node
    environment:
      - NLSR_CONFIG=/NLSR/topologies/linear/nodeB-nlsr.conf
      - GAME=java -jar /NdnGame/NdnGameLibGdxDesktop-1.0-SNAPSHOT.jar -a ws -hl -n  nodeB
    networks:
      private-ndn-overlay:
        aliases:
          - nodeb.ndngame.com
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

networks:
  private-ndn-overlay:
    driver: overlay